[package]
name = "web-push"
description = "Web push notification client with support for http-ece encryption and VAPID authentication."
version = "0.7.3"
authors = ["Julius de Bruijn <julius+github@nauk.io>"]
license = "Apache-2.0"
homepage = "https://github.com/pimeys/rust-web-push"
repository = "https://github.com/pimeys/rust-web-push"
documentation = "https://docs.rs/web-push/"
readme = "README.md"
keywords = ["web-push", "http-ece", "vapid"]
categories = ["web-programming", "asynchronous"]
edition = "2018"

[badges]
travis-ci = { repository = "pimeys/rust-web-push" }

[dependencies]
futures = "0.3.12"
hyper = {version = "0.14.2", features = ["client", "http2"]}
hyper-tls = "0.5.0"
http = "0.2.3"
serde = "1.0.123"
serde_json = "1.0.61"
serde_derive = "1.0.123"
ring = "0.16.19"
native-tls = "0.2.6"
base64 = "0.13.0"
openssl = "0.10.32"
time = {version = "0.2.25", features = ["std"]}
lazy_static = "1.4.0"
chrono = "0.4.19"
log = "0.4.14"

[dev-dependencies]
argparse = "0.2.2"
tokio = { version = "1.1.1", features = ["macros","rt-multi-thread"] }
